chore: CDK 1.94.2
superluminar-io/super-eks pull request #98
Opened 2021-03-17 09:56 UTC by Miradorn

Use new MultipartUserData Construct to generate NodeTaints

2021-03-17 11:16 UTC, bracki commented on API.md
> +[NodeTaint](#superluminar-io-super-eks-nodetaint)|*No description*
No description sounds suspicious.

2021-03-17 11:18 UTC, bracki requested changes
Apart from the comments does this have any impact on potential users? Or is it an internal thing?

2021-03-17 11:18 UTC, bracki commented on API.md
> +[TaintEffect](#superluminar-io-super-eks-tainteffect)|*No description*
Same as above.

2021-03-17 11:18 UTC, bracki commented on API.md
> +[NodeTaint](#superluminar-io-super-eks-nodetaint)|*No description*
No description sounds suspicious.

2021-03-17 12:09 UTC, Miradorn commented
> Apart from the comments does this have any impact on potential users? Or is it an internal thing?

TBH I'm not totally sure, and I'm going to test it.

Right now I'd guess that the ASG backing the NodeGroup would be updated and new nodes would be rotated in because the userdata does change.

I'd argue that that is OK, since Node rotation is a "normal" thing that happens all the time.

But I will test it before merging.

2021-03-19 09:19 UTC, Miradorn commented
Update: unfortunately we have to introduce a breaking change, since the cluster cannot be migrated due to naming and scope conflicts.
Since we're pre 1.0.0 we're ok with this.

2021-03-19 15:30 UTC, bracki approved these changes

2021-03-19 15:31 UTC, merged